### ISSUE TITLE
This repo dismatch with the online version

### ISSUE THREAD

**Issue by aloisdg** [ionic-team/ionic-present#6]
Hello,

Clone the repository and compare with the [online version](http://ionicframework.com/present-ionic/slides/#). Which one is the updated one? I am pretty sure the online one is outdated. It could be a good idea to update it.

**Comment by Ionitron** [comment]
Greetings @aloisdg!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
