### ISSUE TITLE
Small typo, GitHub is misnamed Github

### ISSUE THREAD

**Issue by aloisdg** [ionic-team/ionic-present#7]
Hello,

During the translation to french, I found three small typos. GitHub is written as GitHub in the slide 38.

![typoionic](https://cloud.githubusercontent.com/assets/3449303/7879997/b55b4da6-05f5-11e5-9a21-165dd40a42c1.PNG)

Cheers,

**Comment by Ionitron** [comment]
Greetings @aloisdg!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
